Repository cloudwego/kitex, pull requests merged in 2021-07, with the labels that each got.

#1 docs: add combine service instruction
  README.md
  docs/guide/basic-features/combine_service_cn.md
Labels: documentation

#12 *: fix some minor typos
  docs/guide/basic-features/circuitbreaker_cn.md
Labels: documentation

#20 修复一些 golint 错误
  internal/client/lock.go
  internal/mocks/transhandlerclient.go
  pkg/remote/bound/transmeta_bound.go
  pkg/remote/codec/perrors/protocol_error.go
  pkg/remote/codec/protobuf/protobuf.go
  pkg/remote/codec/protobuf/protobuf_test.go
  pkg/remote/codec/thrift/binary_protocol_test.go
  pkg/remote/codec/thrift/thrift.go
  pkg/remote/remotecli/conn_wrapper.go
  pkg/remote/trans/nphttp2/doc.go
  pkg/utils/max_counter.go
  server/hooks.go
  server/option_advanced.go
Labels: lint

#31 Fail fast
  tool/cmd/kitex/args.go
  tool/internal/pkg/util/util.go
Labels: optimization

#39 docs: fix description of interaction_cn.md
  docs/guide/basic-features/interaction_cn.md
Labels: documentation
